### ISSUE TITLE
Example for calling special.beta() is not working? How to call scipy.special.ndtr?

### ISSUE THREAD

**Issue by cs224** [numba/numba-scipy#45]
Hello, I am trying to follow the example in [Numba 0.46.0 Release Demo](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks/Numba_046_release_demo.ipynb), but it does not seem to work:

```
from numba import jit, njit, config, __version__, errors
from numba.extending import overload
import numba
import numpy as np
assert tuple(int(x) for x in __version__.split('.')[:2]) >= (0, 46)

from scipy import special

@njit
def call_scipy_in_jitted_code():
    return special.beta(1.2, 3.4)
    
call_scipy_in_jitted_code()

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'beta' of type Module(<module 'scipy.special' from '/anaconda3-2020.07-Linux-x86_64/envs/py36dspf/lib/python3.6/site-packages/scipy/special/__init__.py'>)

File "<ipython-input-2-6f63370e200c>", line 5:
def call_scipy_in_jitted_code():
    return special.beta(1.2, 3.4)
```
I am using

- numba 0.51.2
- numba_scipy 0.2.0

What I actually really would like to achieve is to call `scipy.special.ndtr`. I've found an example on how to do it at:[support for scipy.special functions : feature request](https://github.com/numba/numba/issues/3086):

```
_dble = ctypes.c_double

addr = numba.extending.get_cython_function_address("scipy.special.cython_special", "__pyx_fuse_1ndtr")
functype = ctypes.CFUNCTYPE(_dble, _dble)
ndtr_float64_fn = functype(addr)

@numba.njit()
def call_ndtr(v):
    return ndtr_float64_fn(v)

call_ndtr(0.1)
0.539827837277029
```

This works for a single value, but it does not work for an array as input:

```
call_ndtr(np.array([0.1,0.2]))

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function ExternalFunctionPointer((float64,) -> float64) found for signature:
 
 >>> ExternalFunctionPointer(array(float64, 1d, C))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
...
```

How can I make this work for either case, no matter if I call it on a single value or an array?

Thanks a lot!
Christian

P.S.: by the way: how do I find the correct symbol __pyx_fuse_1ndtr or __pyx_fuse_0ndtr? I see that in ./special/cython_special.cpython-36m-x86_64-linux-gnu.so there are both symbols defined?

**Comment by cs224** [comment]
I guess I know now why the example for calling special.beta() is not working. Most likely due to [Error with the latest scipy](https://github.com/numba/numba-scipy/issues/35). I use scipy 1.5.2 and I get the following warning:

```
UserWarning: Numba extension module 'numba_scipy' failed to load due to 'ValueError(No function '__pyx_fuse_0pdtr' found in __pyx_capi__ of 'scipy.special.cython_special')'.
```

**Comment by esc** [comment]
I reckon this is a duplicate of #44 ? There are some changes in #54 to fix this issue, @cs224 if you have time and inclination, please do check if the proposed solution works for you, thank you!

**Comment by cs224** [comment]
@esc: at the moment I have forgotten in which context I tripped over this error. If I remember again I'll try.

**Comment by esc** [comment]
> @esc: at the moment I have forgotten in which context I tripped over this error. If I remember again I'll try.

OK, no worries. I believe now that https://github.com/numba/numba-scipy/pull/54 the examples from the demo notebooks should once again work, i.e. this issue should be resolved. If this is not the case, please don't hesitate to re-open this issue or maybe open a new one. Thank you for using Numba-scipy!

**Comment by lzkelley** [comment]
I'm still getting the same error `UserWarning: Numba extension module 'numba_scipy' failed to load due to 'ValueError(No function '__pyx_fuse_0pdtr' found in pyx_capi of 'scipy.special.cython_special')'.`

```
import sys
import numpy
import numba
from numba import njit
import scipy

print(sys.version)
print(sys. version_info)

print(f"{numpy.__version__=}")
print(f"{numba.__version__=}")
print(f"{scipy.__version__=}")


@njit
def foo(x):
    return scipy.special.j0(x)


print(foo(0.2))
```

this gives:

> 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:27:35) [Clang 14.0.6 ]
> sys.version_info(major=3, minor=10, micro=8, releaselevel='final', serial=0)
> numpy.__version__='1.23.5'
> numba.__version__='0.56.4'
> scipy.__version__='1.10.0'
> /opt/anaconda3/envs/py310/lib/python3.10/site-packages/numba/core/dispatcher.py:289: UserWarning: Numba extension module 'numba_scipy' failed to load due to 'ValueError(No function '__pyx_fuse_0pdtr' found in __pyx_capi__ of 'scipy.special.cython_special')'.
>   entrypoints.init_all()
> Traceback (most recent call last):
>   File "/Users/lzkelley/programs/nanograv/holodeck/test.py", line 20, in <module>
>     print(foo(0.2))
>   File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
>     error_rewrite(e, 'typing')
>   File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
>     raise e.with_traceback(None)
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> Unknown attribute 'j0' of type Module(<module 'scipy.special' from '/opt/anaconda3/envs/py310/lib/python3.10/site-packages/scipy/special/__init__.py'>)
> 
> File "test.py", line 17:
> def foo(x):
>     return scipy.special.j0(x)
>     ^
> 
> During: typing of get attribute at /Users/lzkelley/programs/nanograv/holodeck/test.py (17)
> 
> File "test.py", line 17:
> def foo(x):
>     return scipy.special.j0(x)
>
